--------------------------------------------------------
-- Archivo creado  - jueves-septiembre-25-2025   
--------------------------------------------------------
DROP SEQUENCE "QUICKMARKET_USER"."SQ_CATEGORIAS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_CLIENTES";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_DETALLE_VENTAS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_PRODUCTOS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_USUARIOS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_VENTAS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_CATEGORIAS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_CLIENTES";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_PRODUCTOS";
DROP SEQUENCE "QUICKMARKET_USER"."SQ_USUARIOS";
DROP TABLE "QUICKMARKET_USER"."CATEGORIAS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."CLIENTES" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."PRODUCTOS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."USUARIOS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."VENTAS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."USUARIOS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."PRODUCTOS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."VENTAS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."CATEGORIAS" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."CLIENTES" cascade constraints;
DROP TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" cascade constraints;
DROP PROCEDURE "QUICKMARKET_USER"."SP_CREAR_VENTA";
DROP SYNONYM "PUBLIC"."PLITBLM";
DROP SYNONYM "PUBLIC"."DBMS_LOB";
--------------------------------------------------------
--  DDL for Sequence SQ_CATEGORIAS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_CATEGORIAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_CLIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_CLIENTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_DETALLE_VENTAS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_DETALLE_VENTAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_PRODUCTOS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_PRODUCTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_VENTAS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_VENTAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_CATEGORIAS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_CATEGORIAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_CLIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_CLIENTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_PRODUCTOS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_PRODUCTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SQ_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "QUICKMARKET_USER"."SQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."CATEGORIAS" 
   (	"ID_CATEGORIA" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"TELEFONO" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"DEPARTAMENTO" VARCHAR2(80 BYTE), 
	"MUNICIPIO" VARCHAR2(80 BYTE), 
	"REFERENCIA" VARCHAR2(200 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_VENTAS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" 
   (	"ID_DETALLE" NUMBER, 
	"ID_VENTA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER(12,3), 
	"PRECIO_UNITARIO" NUMBER(12,2), 
	"SUBTOTAL" NUMBER GENERATED ALWAYS AS ("CANTIDAD"*"PRECIO_UNITARIO") VIRTUAL , 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER, 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"DESCRIPCION" VARCHAR2(120 BYTE), 
	"PRECIO_UNITARIO" NUMBER(12,2), 
	"STOCK" NUMBER(12,3) DEFAULT 0, 
	"ID_CATEGORIA" NUMBER, 
	"IVA_UNITARIO" NUMBER GENERATED ALWAYS AS (ROUND("PRECIO_UNITARIO"*0.12,2)) VIRTUAL , 
	"PRECIO_CON_IVA" NUMBER GENERATED ALWAYS AS ("PRECIO_UNITARIO"+ROUND("PRECIO_UNITARIO"*0.12,2)) VIRTUAL , 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"ROL" VARCHAR2(20 BYTE) DEFAULT 'cliente', 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'activo', 
	"RESET_TOKEN" VARCHAR2(255 BYTE), 
	"RESET_EXPIRA" TIMESTAMP (6), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."VENTAS" 
   (	"ID_VENTA" NUMBER, 
	"FECHA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ID_CLIENTE" NUMBER, 
	"TOTAL_BRUTO" NUMBER(12,2) DEFAULT 0, 
	"TOTAL_IMPUESTOS" NUMBER(12,2) DEFAULT 0, 
	"TOTAL_NETO" NUMBER(12,2) DEFAULT 0, 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"PASSWORD_HASH" VARCHAR2(255 BYTE), 
	"ROL" VARCHAR2(20 BYTE) DEFAULT 'cliente', 
	"ESTADO" VARCHAR2(20 BYTE) DEFAULT 'activo', 
	"RESET_TOKEN" VARCHAR2(255 BYTE), 
	"RESET_EXPIRA" TIMESTAMP (6), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER, 
	"NOMBRE" VARCHAR2(120 BYTE), 
	"DESCRIPCION" VARCHAR2(120 BYTE), 
	"PRECIO_UNITARIO" NUMBER(12,2), 
	"STOCK" NUMBER(12,3) DEFAULT 0, 
	"ID_CATEGORIA" NUMBER, 
	"IVA_UNITARIO" NUMBER GENERATED ALWAYS AS (ROUND("PRECIO_UNITARIO"*0.12,2)) VIRTUAL , 
	"PRECIO_CON_IVA" NUMBER GENERATED ALWAYS AS ("PRECIO_UNITARIO"+ROUND("PRECIO_UNITARIO"*0.12,2)) VIRTUAL , 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."VENTAS" 
   (	"ID_VENTA" NUMBER, 
	"FECHA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ID_CLIENTE" NUMBER, 
	"TOTAL_BRUTO" NUMBER(12,2) DEFAULT 0, 
	"TOTAL_IMPUESTOS" NUMBER(12,2) DEFAULT 0, 
	"TOTAL_NETO" NUMBER(12,2) DEFAULT 0, 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."CATEGORIAS" 
   (	"ID_CATEGORIA" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(150 BYTE), 
	"TELEFONO" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"DEPARTAMENTO" VARCHAR2(80 BYTE), 
	"MUNICIPIO" VARCHAR2(80 BYTE), 
	"REFERENCIA" VARCHAR2(200 BYTE), 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_VENTAS
--------------------------------------------------------

  CREATE TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" 
   (	"ID_DETALLE" NUMBER, 
	"ID_VENTA" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER(12,3), 
	"PRECIO_UNITARIO" NUMBER(12,2), 
	"SUBTOTAL" NUMBER GENERATED ALWAYS AS ("CANTIDAD"*"PRECIO_UNITARIO") VIRTUAL , 
	"CREADO_EN" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"ACTUALIZADO_EN" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
REM INSERTING into QUICKMARKET_USER.CATEGORIAS
SET DEFINE OFF;
Insert into QUICKMARKET_USER.CATEGORIAS (ID_CATEGORIA,NOMBRE,DESCRIPCION,CREADO_EN,ACTUALIZADO_EN) values (2,'frutas','Productos de abarrotería',to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null);
REM INSERTING into QUICKMARKET_USER.CLIENTES
SET DEFINE OFF;
Insert into QUICKMARKET_USER.CLIENTES (ID_CLIENTE,ID_USUARIO,NOMBRE,TELEFONO,DIRECCION,DEPARTAMENTO,MUNICIPIO,REFERENCIA,CREADO_EN,ACTUALIZADO_EN) values (1,4,'Juan P. Actualizado','555-9999','Av. Siempre Viva 742','Guatemala','Mixco','Frente a la tienda',to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('25/09/25 04:15:10.302000000 PM','DD/MM/RR HH12:MI:SSXFF AM'));
REM INSERTING into QUICKMARKET_USER.DETALLE_VENTAS
SET DEFINE OFF;
REM INSERTING into QUICKMARKET_USER.PRODUCTOS
SET DEFINE OFF;
REM INSERTING into QUICKMARKET_USER.USUARIOS
SET DEFINE OFF;
Insert into QUICKMARKET_USER.USUARIOS (ID_USUARIO,USERNAME,EMAIL,PASSWORD_HASH,ROL,ESTADO,RESET_TOKEN,RESET_EXPIRA,CREADO_EN,ACTUALIZADO_EN) values (3,'osbeli','osbelitojin@gmail.com','$2a$11$RRdzAaGDaK6kxuAtBB2ELOYLei1hXkutBaZHiI9M.LqjfTPaS64A2','administrador','activo',null,null,to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('24/09/25 10:04:31.059000000 PM','DD/MM/RR HH12:MI:SSXFF AM'));
Insert into QUICKMARKET_USER.USUARIOS (ID_USUARIO,USERNAME,EMAIL,PASSWORD_HASH,ROL,ESTADO,RESET_TOKEN,RESET_EXPIRA,CREADO_EN,ACTUALIZADO_EN) values (4,'alex','alexander2004deleon@gmail.com','$2a$11$zAsjZUOjLqnjUxxmCZLQ9eldcOEKkQx/Ub7kJ.aAmROHiLQ86YvKu','cliente','activo',null,null,to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null);
Insert into QUICKMARKET_USER.USUARIOS (ID_USUARIO,USERNAME,EMAIL,PASSWORD_HASH,ROL,ESTADO,RESET_TOKEN,RESET_EXPIRA,CREADO_EN,ACTUALIZADO_EN) values (5,'cliente','asdsadsd@gmail.com','$2a$11$F6XnMkLDOuQeHre7wdtWm.LI3CqqCPQ273lW9tt9S/qvwv4/bPX.q','cliente','activo',null,null,to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null);
Insert into QUICKMARKET_USER.USUARIOS (ID_USUARIO,USERNAME,EMAIL,PASSWORD_HASH,ROL,ESTADO,RESET_TOKEN,RESET_EXPIRA,CREADO_EN,ACTUALIZADO_EN) values (1,'admin','alexanderdeleon0431@gmail.com','$2a$11$VwXLHdyQeSUO/Mgc4jqk..gKSJpLHq1oJrQV9aAlsI6pZW/uW82um','administrador','activo',null,null,to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('24/09/25 03:55:23.770000000 PM','DD/MM/RR HH12:MI:SSXFF AM'));
Insert into QUICKMARKET_USER.USUARIOS (ID_USUARIO,USERNAME,EMAIL,PASSWORD_HASH,ROL,ESTADO,RESET_TOKEN,RESET_EXPIRA,CREADO_EN,ACTUALIZADO_EN) values (2,'eduardo','gutierrezlimacesareduardo@gmail.com','$2a$11$JQvqLcfQFD7FI5UlTLVBAeQs.E6DlLiNkG/aLzEtEV4WVUGcnkXHi','administrador','activo',null,null,to_timestamp('01/01/01 12:00:00.000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),to_timestamp('24/09/25 04:04:52.046000000 PM','DD/MM/RR HH12:MI:SSXFF AM'));
REM INSERTING into QUICKMARKET_USER.VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IX_DETALLE_VENTAS_PRODUCTO
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_DETALLE_VENTAS_PRODUCTO" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_DETALLE_VENTAS_VENTA
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_DETALLE_VENTAS_VENTA" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_PRODUCTOS_CATEGORIA
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_PRODUCTOS_CATEGORIA" ON "QUICKMARKET_USER"."PRODUCTOS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_PRODUCTOS_NOMBRE
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_PRODUCTOS_NOMBRE" ON "QUICKMARKET_USER"."PRODUCTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_VENTAS_CLIENTE
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_VENTAS_CLIENTE" ON "QUICKMARKET_USER"."VENTAS" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011647
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011647" ON "QUICKMARKET_USER"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011650
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011650" ON "QUICKMARKET_USER"."CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011654
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011654" ON "QUICKMARKET_USER"."CATEGORIAS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011662
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011662" ON "QUICKMARKET_USER"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011671
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011671" ON "QUICKMARKET_USER"."VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011680
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011680" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_CLIENTES_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_CLIENTES_ID_USUARIO" ON "QUICKMARKET_USER"."CLIENTES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_DET_VENTA_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_DET_VENTA_PRODUCTO" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_VENTA", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIOS_EMAIL_CI
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_USUARIOS_EMAIL_CI" ON "QUICKMARKET_USER"."USUARIOS" (UPPER("EMAIL")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIOS_USERNAME_CI
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_USUARIOS_USERNAME_CI" ON "QUICKMARKET_USER"."USUARIOS" (UPPER("USERNAME")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011654
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011654" ON "QUICKMARKET_USER"."CATEGORIAS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011650
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011650" ON "QUICKMARKET_USER"."CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_CLIENTES_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_CLIENTES_ID_USUARIO" ON "QUICKMARKET_USER"."CLIENTES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_DETALLE_VENTAS_VENTA
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_DETALLE_VENTAS_VENTA" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_DETALLE_VENTAS_PRODUCTO
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_DETALLE_VENTAS_PRODUCTO" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011680
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011680" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_DET_VENTA_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_DET_VENTA_PRODUCTO" ON "QUICKMARKET_USER"."DETALLE_VENTAS" ("ID_VENTA", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011662
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011662" ON "QUICKMARKET_USER"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_PRODUCTOS_CATEGORIA
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_PRODUCTOS_CATEGORIA" ON "QUICKMARKET_USER"."PRODUCTOS" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_PRODUCTOS_NOMBRE
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_PRODUCTOS_NOMBRE" ON "QUICKMARKET_USER"."PRODUCTOS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011647
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011647" ON "QUICKMARKET_USER"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIOS_USERNAME_CI
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_USUARIOS_USERNAME_CI" ON "QUICKMARKET_USER"."USUARIOS" (UPPER("USERNAME")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index UQ_USUARIOS_EMAIL_CI
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."UQ_USUARIOS_EMAIL_CI" ON "QUICKMARKET_USER"."USUARIOS" (UPPER("EMAIL")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011671
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUICKMARKET_USER"."SYS_C0011671" ON "QUICKMARKET_USER"."VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Index IX_VENTAS_CLIENTE
--------------------------------------------------------

  CREATE INDEX "QUICKMARKET_USER"."IX_VENTAS_CLIENTE" ON "QUICKMARKET_USER"."VENTAS" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS" ;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_CATEGORIAS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_CATEGORIAS_ID" 
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_CATEGORIA IS NULL THEN
    :NEW.ID_CATEGORIA := SQ_CATEGORIAS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_CATEGORIAS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_CLIENTES_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_CLIENTES_ID" 
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
  IF :NEW.ID_CLIENTE IS NULL THEN
    :NEW.ID_CLIENTE := SQ_CLIENTES.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_CLIENTES_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_DETALLE_VENTAS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_DETALLE_VENTAS_ID" 
BEFORE INSERT ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_DETALLE IS NULL THEN
    :NEW.ID_DETALLE := SQ_DETALLE_VENTAS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_DETALLE_VENTAS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_PRODUCTOS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_PRODUCTOS_ID" 
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_PRODUCTO IS NULL THEN
    :NEW.ID_PRODUCTO := SQ_PRODUCTOS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_PRODUCTOS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_USUARIOS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_USUARIOS_ID" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    :NEW.ID_USUARIO := SQ_USUARIOS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_USUARIOS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_VENTAS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_VENTAS_ID" 
BEFORE INSERT ON VENTAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_VENTA IS NULL THEN
    :NEW.ID_VENTA := SQ_VENTAS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_VENTAS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_STOCK_AD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_AD" 
AFTER DELETE ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
  UPDATE PRODUCTOS
     SET STOCK = STOCK + :OLD.CANTIDAD
   WHERE ID_PRODUCTO = :OLD.ID_PRODUCTO;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_AD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_STOCK_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_BI" 
BEFORE INSERT OR UPDATE OF CANTIDAD, PRECIO_UNITARIO, ID_PRODUCTO ON DETALLE_VENTAS
FOR EACH ROW
DECLARE
  v_stock NUMBER;
BEGIN
  IF INSERTING THEN
    IF :NEW.CANTIDAD <= 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'Cantidad debe ser > 0');
    END IF;

    SELECT STOCK INTO v_stock
      FROM PRODUCTOS
     WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO
     FOR UPDATE;

    IF v_stock < :NEW.CANTIDAD THEN
      RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente');
    END IF;

    UPDATE PRODUCTOS
       SET STOCK = STOCK - :NEW.CANTIDAD
     WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

  ELSIF UPDATING THEN
    IF :OLD.ID_PRODUCTO <> :NEW.ID_PRODUCTO THEN
      -- Regresa cantidad al producto anterior
      UPDATE PRODUCTOS
         SET STOCK = STOCK + :OLD.CANTIDAD
       WHERE ID_PRODUCTO = :OLD.ID_PRODUCTO;

      -- Descuenta en el nuevo producto
      SELECT STOCK INTO v_stock
        FROM PRODUCTOS
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO
       FOR UPDATE;

      IF :NEW.CANTIDAD <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cantidad debe ser > 0');
      END IF;

      IF v_stock < :NEW.CANTIDAD THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente para el nuevo producto');
      END IF;

      UPDATE PRODUCTOS
         SET STOCK = STOCK - :NEW.CANTIDAD
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    ELSE
      -- Mismo producto: ajusta por diferencia
      UPDATE PRODUCTOS
         SET STOCK = STOCK + :OLD.CANTIDAD - :NEW.CANTIDAD
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

      SELECT STOCK INTO v_stock
        FROM PRODUCTOS
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

      IF v_stock < 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente al actualizar');
      END IF;
    END IF;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NORM_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_NORM_CLIENTES" 
BEFORE INSERT OR UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
  IF :NEW.NOMBRE       IS NOT NULL THEN :NEW.NOMBRE       := TRIM(:NEW.NOMBRE);       END IF;
  IF :NEW.TELEFONO     IS NOT NULL THEN :NEW.TELEFONO     := TRIM(:NEW.TELEFONO);     END IF;
  IF :NEW.DIRECCION    IS NOT NULL THEN :NEW.DIRECCION    := TRIM(:NEW.DIRECCION);    END IF;
  IF :NEW.DEPARTAMENTO IS NOT NULL THEN :NEW.DEPARTAMENTO := TRIM(:NEW.DEPARTAMENTO); END IF;
  IF :NEW.MUNICIPIO    IS NOT NULL THEN :NEW.MUNICIPIO    := TRIM(:NEW.MUNICIPIO);    END IF;
  IF :NEW.REFERENCIA   IS NOT NULL THEN :NEW.REFERENCIA   := TRIM(:NEW.REFERENCIA);   END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_NORM_CLIENTES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NORM_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_NORM_USUARIOS" 
BEFORE INSERT OR UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
  :NEW.USERNAME := TRIM(:NEW.USERNAME);
  :NEW.EMAIL    := TRIM(:NEW.EMAIL);
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_NORM_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_CATEGORIAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_CATEGORIAS" 
BEFORE UPDATE ON CATEGORIAS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_CATEGORIAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_CLIENTES" 
BEFORE UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_CLIENTES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_DETALLE_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_DETALLE_VENTAS" 
BEFORE UPDATE ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_DETALLE_VENTAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_PRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_PRODUCTOS" 
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_PRODUCTOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_USUARIOS" 
BEFORE UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_VENTAS" 
BEFORE UPDATE ON VENTAS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_VENTAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_VENTAS_RECALC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_VENTAS_RECALC" 
FOR INSERT OR UPDATE OR DELETE ON DETALLE_VENTAS
COMPOUND TRIGGER
  TYPE t_ids IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  g_ids t_ids;

  PROCEDURE add_id(p_id NUMBER) IS
  BEGIN
    IF p_id IS NOT NULL THEN
      FOR i IN 1 .. g_ids.COUNT LOOP
        IF g_ids(i) = p_id THEN RETURN; END IF;
      END LOOP;
      g_ids(g_ids.COUNT + 1) := p_id;
    END IF;
  END;

  AFTER EACH ROW IS
  BEGIN
    IF INSERTING OR UPDATING THEN
      add_id(:NEW.ID_VENTA);
    ELSIF DELETING THEN
      add_id(:OLD.ID_VENTA);
    END IF;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
    v_tasa CONSTANT NUMBER := 0.12;
  BEGIN
    FOR i IN 1 .. g_ids.COUNT LOOP
      UPDATE VENTAS v
         SET (TOTAL_BRUTO, TOTAL_IMPUESTOS, TOTAL_NETO) = (
               SELECT NVL(SUM(d.SUBTOTAL), 0),
                      ROUND(NVL(SUM(d.SUBTOTAL), 0) * v_tasa, 2),
                      NVL(SUM(d.SUBTOTAL), 0) + ROUND(NVL(SUM(d.SUBTOTAL), 0) * v_tasa, 2)
                 FROM DETALLE_VENTAS d
                WHERE d.ID_VENTA = v.ID_VENTA
             )
       WHERE v.ID_VENTA = g_ids(i);
    END LOOP;
  END AFTER STATEMENT;
END TRG_VENTAS_RECALC;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_VENTAS_RECALC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_CATEGORIAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_CATEGORIAS" 
BEFORE UPDATE ON CATEGORIAS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_CATEGORIAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_CATEGORIAS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_CATEGORIAS_ID" 
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_CATEGORIA IS NULL THEN
    :NEW.ID_CATEGORIA := SQ_CATEGORIAS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_CATEGORIAS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NORM_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_NORM_CLIENTES" 
BEFORE INSERT OR UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
  IF :NEW.NOMBRE       IS NOT NULL THEN :NEW.NOMBRE       := TRIM(:NEW.NOMBRE);       END IF;
  IF :NEW.TELEFONO     IS NOT NULL THEN :NEW.TELEFONO     := TRIM(:NEW.TELEFONO);     END IF;
  IF :NEW.DIRECCION    IS NOT NULL THEN :NEW.DIRECCION    := TRIM(:NEW.DIRECCION);    END IF;
  IF :NEW.DEPARTAMENTO IS NOT NULL THEN :NEW.DEPARTAMENTO := TRIM(:NEW.DEPARTAMENTO); END IF;
  IF :NEW.MUNICIPIO    IS NOT NULL THEN :NEW.MUNICIPIO    := TRIM(:NEW.MUNICIPIO);    END IF;
  IF :NEW.REFERENCIA   IS NOT NULL THEN :NEW.REFERENCIA   := TRIM(:NEW.REFERENCIA);   END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_NORM_CLIENTES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_CLIENTES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_CLIENTES" 
BEFORE UPDATE ON CLIENTES
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_CLIENTES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_CLIENTES_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_CLIENTES_ID" 
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
  IF :NEW.ID_CLIENTE IS NULL THEN
    :NEW.ID_CLIENTE := SQ_CLIENTES.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_CLIENTES_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_DETALLE_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_DETALLE_VENTAS" 
BEFORE UPDATE ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_DETALLE_VENTAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_DETALLE_VENTAS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_DETALLE_VENTAS_ID" 
BEFORE INSERT ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_DETALLE IS NULL THEN
    :NEW.ID_DETALLE := SQ_DETALLE_VENTAS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_DETALLE_VENTAS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_STOCK_BI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_BI" 
BEFORE INSERT OR UPDATE OF CANTIDAD, PRECIO_UNITARIO, ID_PRODUCTO ON DETALLE_VENTAS
FOR EACH ROW
DECLARE
  v_stock NUMBER;
BEGIN
  IF INSERTING THEN
    IF :NEW.CANTIDAD <= 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'Cantidad debe ser > 0');
    END IF;

    SELECT STOCK INTO v_stock
      FROM PRODUCTOS
     WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO
     FOR UPDATE;

    IF v_stock < :NEW.CANTIDAD THEN
      RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente');
    END IF;

    UPDATE PRODUCTOS
       SET STOCK = STOCK - :NEW.CANTIDAD
     WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

  ELSIF UPDATING THEN
    IF :OLD.ID_PRODUCTO <> :NEW.ID_PRODUCTO THEN
      -- Regresa cantidad al producto anterior
      UPDATE PRODUCTOS
         SET STOCK = STOCK + :OLD.CANTIDAD
       WHERE ID_PRODUCTO = :OLD.ID_PRODUCTO;

      -- Descuenta en el nuevo producto
      SELECT STOCK INTO v_stock
        FROM PRODUCTOS
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO
       FOR UPDATE;

      IF :NEW.CANTIDAD <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cantidad debe ser > 0');
      END IF;

      IF v_stock < :NEW.CANTIDAD THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente para el nuevo producto');
      END IF;

      UPDATE PRODUCTOS
         SET STOCK = STOCK - :NEW.CANTIDAD
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

    ELSE
      -- Mismo producto: ajusta por diferencia
      UPDATE PRODUCTOS
         SET STOCK = STOCK + :OLD.CANTIDAD - :NEW.CANTIDAD
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

      SELECT STOCK INTO v_stock
        FROM PRODUCTOS
       WHERE ID_PRODUCTO = :NEW.ID_PRODUCTO;

      IF v_stock < 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente al actualizar');
      END IF;
    END IF;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_DETALLE_STOCK_AD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_AD" 
AFTER DELETE ON DETALLE_VENTAS
FOR EACH ROW
BEGIN
  UPDATE PRODUCTOS
     SET STOCK = STOCK + :OLD.CANTIDAD
   WHERE ID_PRODUCTO = :OLD.ID_PRODUCTO;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_DETALLE_STOCK_AD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_VENTAS_RECALC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_VENTAS_RECALC" 
FOR INSERT OR UPDATE OR DELETE ON DETALLE_VENTAS
COMPOUND TRIGGER
  TYPE t_ids IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  g_ids t_ids;

  PROCEDURE add_id(p_id NUMBER) IS
  BEGIN
    IF p_id IS NOT NULL THEN
      FOR i IN 1 .. g_ids.COUNT LOOP
        IF g_ids(i) = p_id THEN RETURN; END IF;
      END LOOP;
      g_ids(g_ids.COUNT + 1) := p_id;
    END IF;
  END;

  AFTER EACH ROW IS
  BEGIN
    IF INSERTING OR UPDATING THEN
      add_id(:NEW.ID_VENTA);
    ELSIF DELETING THEN
      add_id(:OLD.ID_VENTA);
    END IF;
  END AFTER EACH ROW;

  AFTER STATEMENT IS
    v_tasa CONSTANT NUMBER := 0.12;
  BEGIN
    FOR i IN 1 .. g_ids.COUNT LOOP
      UPDATE VENTAS v
         SET (TOTAL_BRUTO, TOTAL_IMPUESTOS, TOTAL_NETO) = (
               SELECT NVL(SUM(d.SUBTOTAL), 0),
                      ROUND(NVL(SUM(d.SUBTOTAL), 0) * v_tasa, 2),
                      NVL(SUM(d.SUBTOTAL), 0) + ROUND(NVL(SUM(d.SUBTOTAL), 0) * v_tasa, 2)
                 FROM DETALLE_VENTAS d
                WHERE d.ID_VENTA = v.ID_VENTA
             )
       WHERE v.ID_VENTA = g_ids(i);
    END LOOP;
  END AFTER STATEMENT;
END TRG_VENTAS_RECALC;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_VENTAS_RECALC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_PRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_PRODUCTOS" 
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_PRODUCTOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_PRODUCTOS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_PRODUCTOS_ID" 
BEFORE INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_PRODUCTO IS NULL THEN
    :NEW.ID_PRODUCTO := SQ_PRODUCTOS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_PRODUCTOS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_USUARIOS" 
BEFORE UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_USUARIOS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_USUARIOS_ID" 
BEFORE INSERT ON USUARIOS
FOR EACH ROW
BEGIN
  IF :NEW.ID_USUARIO IS NULL THEN
    :NEW.ID_USUARIO := SQ_USUARIOS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_USUARIOS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_NORM_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_NORM_USUARIOS" 
BEFORE INSERT OR UPDATE ON USUARIOS
FOR EACH ROW
BEGIN
  :NEW.USERNAME := TRIM(:NEW.USERNAME);
  :NEW.EMAIL    := TRIM(:NEW.EMAIL);
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_NORM_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_TS_VENTAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_TS_VENTAS" 
BEFORE UPDATE ON VENTAS
FOR EACH ROW
BEGIN
  :NEW.ACTUALIZADO_EN := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_TS_VENTAS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_BI_VENTAS_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "QUICKMARKET_USER"."TRG_BI_VENTAS_ID" 
BEFORE INSERT ON VENTAS
FOR EACH ROW
BEGIN
  IF :NEW.ID_VENTA IS NULL THEN
    :NEW.ID_VENTA := SQ_VENTAS.NEXTVAL;
  END IF;
END;

/
ALTER TRIGGER "QUICKMARKET_USER"."TRG_BI_VENTAS_ID" ENABLE;
--------------------------------------------------------
--  DDL for Procedure SP_CREAR_VENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "QUICKMARKET_USER"."SP_CREAR_VENTA" (
  p_id_cliente IN NUMBER,
  p_items_json IN CLOB,   -- Ej: '[{"id_producto":1,"cantidad":2},{"id_producto":2,"cantidad":3}]'
  p_id_venta   OUT NUMBER
) IS
  v_id_venta  NUMBER;
  v_items_cnt NUMBER := 0;
BEGIN
  -- 0) Validación mínima de entrada
  IF p_id_cliente IS NULL THEN
    RAISE_APPLICATION_ERROR(-20040, 'Debe indicar p_id_cliente.');
  END IF;
  IF p_items_json IS NULL OR DBMS_LOB.getlength(p_items_json) = 0 THEN
    RAISE_APPLICATION_ERROR(-20041, 'Debe enviar p_items_json con al menos un item.');
  END IF;

  -- 1) Crear encabezado de venta
  INSERT INTO VENTAS (ID_CLIENTE)
  VALUES (p_id_cliente)
  RETURNING ID_VENTA INTO v_id_venta;

  -- 2) Insertar detalles desde el JSON
  FOR r IN (
    SELECT
      jt.id_producto,
      jt.cantidad,
      COALESCE(
        jt.precio_unitario,
        (SELECT PRECIO_UNITARIO
           FROM PRODUCTOS
          WHERE ID_PRODUCTO = jt.id_producto)
      ) AS precio_unitario
    FROM JSON_TABLE(
           p_items_json, '$[*]'
           COLUMNS (
             id_producto     NUMBER PATH '$.id_producto',
             cantidad        NUMBER PATH '$.cantidad',
             precio_unitario NUMBER PATH '$.precio_unitario' NULL ON ERROR
           )
         ) jt
  ) LOOP
    -- Validación por ítem
    IF r.id_producto IS NULL THEN
      RAISE_APPLICATION_ERROR(-20050, 'Item inválido: id_producto es NULL.');
    END IF;
    IF r.cantidad IS NULL OR r.cantidad <= 0 THEN
      RAISE_APPLICATION_ERROR(-20051, 'Item inválido: cantidad debe ser > 0.');
    END IF;
    IF r.precio_unitario IS NULL OR r.precio_unitario < 0 THEN
      RAISE_APPLICATION_ERROR(-20052, 'Item inválido: precio_unitario no disponible o negativo.');
    END IF;

    INSERT INTO DETALLE_VENTAS (ID_VENTA, ID_PRODUCTO, CANTIDAD, PRECIO_UNITARIO)
    VALUES (v_id_venta, r.id_producto, r.cantidad, r.precio_unitario);

    v_items_cnt := v_items_cnt + 1;
  END LOOP;

  -- 3) Asegura que hubo al menos un detalle
  IF v_items_cnt = 0 THEN
    RAISE_APPLICATION_ERROR(-20053, 'La venta no tiene ítems (JSON vacío o mal formado).');
  END IF;

  -- 4) Devolver ID generado
  p_id_venta := v_id_venta;

  -- Nota: no hacemos COMMIT aquí a propósito (mejor práctica).
EXCEPTION
  WHEN OTHERS THEN
    -- Si quieres deshacer aquí mismo, descomenta:
    -- ROLLBACK;
    RAISE;
END;

/
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."CATEGORIAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."CATEGORIAS" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."CATEGORIAS" ADD PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."CLIENTES" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."CLIENTES" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_VENTAS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" MODIFY ("PRECIO_UNITARIO" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" ADD CONSTRAINT "CHK_DET_CANT_POS" CHECK (CANTIDAD > 0) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" ADD CONSTRAINT "CHK_DET_PREC_POS" CHECK (PRECIO_UNITARIO >= 0) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" ADD CONSTRAINT "UQ_DET_VENTA_PRODUCTO" UNIQUE ("ID_VENTA", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" MODIFY ("PRECIO_UNITARIO" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" ADD CONSTRAINT "CHK_PRECIO_POSITIVO" CHECK (PRECIO_UNITARIO >= 0) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" ADD CONSTRAINT "CHK_STOCK_NO_NEG" CHECK (STOCK >= 0) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" ADD PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" MODIFY ("PASSWORD_HASH" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" MODIFY ("ROL" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" ADD CHECK (ROL IN ('cliente','administrador')) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."USUARIOS" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."VENTAS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" MODIFY ("TOTAL_BRUTO" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" MODIFY ("TOTAL_IMPUESTOS" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" MODIFY ("TOTAL_NETO" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" MODIFY ("CREADO_EN" NOT NULL ENABLE);
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" ADD CONSTRAINT "CHK_TOTALES_NO_NEG" CHECK (
    TOTAL_BRUTO >= 0 AND TOTAL_IMPUESTOS >= 0 AND TOTAL_NETO >= 0
  ) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" ADD CONSTRAINT "CHK_TOTALES_CONSISTENTES" CHECK (
    ROUND(TOTAL_NETO,2) = ROUND(TOTAL_BRUTO + TOTAL_IMPUESTOS,2)
  ) ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."VENTAS" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "QUICKMARKET_TBS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."CLIENTES" ADD CONSTRAINT "FK_CLIENTE_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "QUICKMARKET_USER"."USUARIOS" ("ID_USUARIO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_VENTAS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" ADD CONSTRAINT "FK_DET_VENTA" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "QUICKMARKET_USER"."VENTAS" ("ID_VENTA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "QUICKMARKET_USER"."DETALLE_VENTAS" ADD CONSTRAINT "FK_DET_PRODUCTO" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "QUICKMARKET_USER"."PRODUCTOS" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."PRODUCTOS" ADD CONSTRAINT "FK_PRODUCTO_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "QUICKMARKET_USER"."CATEGORIAS" ("ID_CATEGORIA") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "QUICKMARKET_USER"."VENTAS" ADD CONSTRAINT "FK_VENTA_CLIENTE" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "QUICKMARKET_USER"."CLIENTES" ("ID_CLIENTE") ON DELETE SET NULL ENABLE;
